import { ICourseCard } from "../types";

export const COURSE_CARD: ICourseCard[] = [
    {
        id: 1,
        title: "VUE JS SCRATCH COURSE",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/vueCourse.png",
    },
    {
        id: 2,
        title: "UI DESIGN FOR BEGINNERS",
        studio: "Kitani Studio",
        desc: "Learn how to make web application with Vue.js Framework.",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/uxUiCourse.png",
    },
    {
        id: 3,
        title: "MOBILE DEV REACT NATIVE",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/reactNativeCourse.png",
    },
    {
        id: 4,
        title: "WEBSITE DEV ZERO TO HERO",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/webDevCourse.png",
    },
    {
        id: 5,
        title: "Adobe Illustrator Scretch Course",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/bootcampCourse.png",
    },
    {
        id: 6,
        title: "Bootcamp  Vue.js Web Framework",
        studio: "Kitani Studio",
        desc: "Learn how to make web application with Vue.js Framework.",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/iosCourse.png",
    },
    {
        id: 7,
        title: "Design Fundamentals",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/designFundCourse.png",
    },
    {
        id: 8,
        title: "Ionic - Build iOS, Android & Web...",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/ionicCourse.png",
    },
    {
        id: 9,
        title: "Adobe Illustrator Scretch Course",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/illustratorCourse.png",
    },
    {
        id: 10,
        title: "Bootcamp  Vue.js Web Framework",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/bootVueCourse.png",
    },
    {
        id: 11,
        title: "Design Fundamentals",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/designCourse.png",
    },
    {
        id: 12,
        title: "Ionic - Build iOS, Android & Web...",
        studio: "Kitani Studio",
        desc: "More than 8yr Experience as Illustrator. Learn how to becoming professional Illustrator Now...",
        price: "$32.90",
        salePrice: "$24.92",
        img: "https://postimage.me/images/2024/08/07/ionicSecondCourse.png",
    },
]